name: Build and deploy

on:
  push:
    branches:
      - main
env:
  cache-version: v1
  GITHUB_PAT: ${{ secrets.GH_SECRET_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: r-base:latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    steps:
    - name: Install pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Install dependencies with apt
      run: |
        apt-get update
        apt-get install -y libcurl4-gnutls-dev texlive-latex-base texlive-fonts-extra git lmodern texlive-latex-recommended texlive-latex-extra rsync libssl-dev

    - name: Restore cached R packages
      if: runner.os != 'Windows'
      uses: actions/cache/restore@v4
      with:
        path: /usr/local/lib/R/site-library
        key: ${{ env.cache-version }}-${{ runner.os }}-r-
        restore-keys: ${{ env.cache-version }}-${{ runner.os }}-r-
        
    - name: Install dependencies with CRAN
      run: |
        options(timeout = max(1000, getOption("timeout")))
        options(repos = c(CRAN = "https://cran.r-project.org"))
        install.packages(c("knitr", "rmarkdown", "BiocManager", "RCurl"))
        BiocManager::install(version="3.19", ask=FALSE, force=TRUE)
        BiocManager::install("Biostrings", ask=FALSE) # for dependencies
        write.csv(installed.packages()[,c(1,3)], file="./dependencies.csv")
      shell: Rscript {0}

    - name: Cache R packages
      if: runner.os != 'Windows'
      uses: actions/cache/save@v4
      with:
        path: /usr/local/lib/R/site-library
        key: ${{ env.cache-version }}-${{ runner.os }}-r-${{ hashFiles('./dependencies.csv') }}

    - name: checkout
      uses: actions/checkout@v4

    - name: re-install Biostrings
      run: |
        remove.packages("Biostrings")
        install.packages("data/Biostrings_2.70.3.tar.gz", repos=NULL)
      shell: Rscript {0}
    
    - name: build
      run: |
        mkdir docs
        Rscript ghgenerate.R
        cp docs/isc-proposal.html docs/index.html
        cp assets/* docs/

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        token: ${{ env.GITHUB_PAT }}
        branch: gh-pages # The branch the action should deploy to.
        folder: docs # The folder the action should deploy.
